### ISSUE TITLE
Code for PRECOG forecasting algorithm?

### ISSUE THREAD

**Issue by GemHou** [nrhine1/precog_carla_dataset#1]
Hello! I am a student working on the vehicle prediction problem at Tongji University. I am interested in your art-of-date PRECOG algorithm, but unfortunately, I have some problem when I try to implement your algorithm. Do you have a plan to open source the PRECOG algorithm? Appreciate your help.

**Comment by nrhinehart** [comment]
Hello! I do plan to release open-source code for PRECOG. It will arrive sometime >= October 2019. I currently don't have much bandwidth for it. If, in the meantime, you have questions about the algorithm, I'm happy to answer!

**Comment by GemHou** [comment]
Really appreciate your help. Many thanks! Best wishes to you!

**Comment by Daniel-1597** [comment]
Hi, GemHou have you implemented anything further I am also trying to do it but struck at GRU cell. please help me if you implemented 
Thank You

**Comment by GemHou** [comment]
Hi, I am sorry that I have not gained too much progress, and this work has been stopped for months. But I will restart it in this month. So just good luck to you.

**Comment by Daniel-1597** [comment]
if you are  going to work on it, please let me know I will also work with you

**Comment by nrhinehart** [comment]
The code is now available here: https://github.com/nrhine1/precog

**Comment by Daniel-1597** [comment]
Thank you sir
